/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chgraphic;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author phant
 */
public class CityScapeJava extends javax.swing.JFrame {

    int width = 1024;
    int heigth = 600;    
    
    Toolkit tools = Toolkit.getDefaultToolkit();
    Image superman = tools.getImage(this.getClass().getResource("super.gif"));

    /**
     * Creates new form CityScapeJava
     */
    public CityScapeJava() {
        initComponents();
        this.setSize(width, heigth);
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        //To change body of generated methods, choose Tools | Templates.
        g.setColor(Color.CYAN);
        g.fillRect(0, 0, width, heigth);
        
        g.drawImage(superman, 50, 50, this);
        
        g.setFont(new Font("Arial", Font.BOLD, 24));
        g.setColor(new Color(255, 0, 100));
        
        g.drawString("Click to redraw", 220, 100);
        //draw the sun
        
        g.setColor(Color.yellow);
        g.fillOval(700, 45, 80, 80);

        /*  g.setColor(Color.BLUE);
               g.fillRect(0, 400, 55, 200);//floating building
               g.fillRect(300, 250, 80, (heigth -250));
               g.fillRect(500, WIDTH, WIDTH, WIDTH);
         */
        ranBuiling(g);
    }
    
    private void ranBuiling(Graphics g) {
        int Startx, Starty, wid, hei, red, green, blue;
        int win, winX, winY, numWin;

        //building up to 60 to 260 ox wide
        //Height 200-500 px
        for (int i = 0; i < 15; i++) {
            Startx = (int) (Math.random() * (width - 100)); //generates 0-924 px
            Starty = (int) (200 + Math.random() * 300);//200-500 px
            wid = (int) (60 + Math.random() * 200); //between 60 and 260 px
            hei = heigth - Starty;
            
            red = (int) (Math.random() * 255);
            green = (int) (Math.random() * 255);
            blue = (int) (Math.random() * 255);
            
            g.setColor(new Color(red, green, blue));
            g.fillRect(Startx, Starty, wid, hei);
          //  g.setColor(Color.black);
            g.fillRect(Startx, Starty, wid, hei);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == evt.BUTTON1) {
            repaint();
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CityScapeJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CityScapeJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CityScapeJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CityScapeJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CityScapeJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
