/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chgraphic;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author phant
 */
public class GraphicFoem extends javax.swing.JFrame {

    /**
     * Creates new form GraphicFoem
     */
    public GraphicFoem() {
        initComponents();
        
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
drawGrid(g);
        /*
     Paint draws a screemw   
        */        
//To change body of generated methods, choose Tools | Templates.
    g.setColor(Color.BLUE);
    g.fillRect(50, 50, 100, 200);
    
    g.setColor(Color.BLACK);
    g.drawLine(20, 600, 170, 30);
    
    g.setColor(Color.RED);
    g.fillRect(20, 150, 250, 30);
    
    
    // better graphics
Graphics2D  draw = (Graphics2D) g;
//draw.setColor(new Color(255,255,255));


Color purple = new Color(200,0, 200);
draw.setColor(purple);

BasicStroke pen =  new BasicStroke(5, BasicStroke.CAP_ROUND,BasicStroke.JOIN_MITER);
draw.setStroke(pen);

draw.drawLine(20, 400, this.getWidth(), 400);


draw.setColor(purple);
//draw.fillArc(160, 170, 100, 100, 0, 360);
draw.setColor(purple);
draw.fillArc(160, 170, 100, 100,20,320);
    }
    public  void drawGrid(Graphics g){
        g.setColor(new Color (100,0,255));
        g.fillRect(0, 0, this.getWidth(), this.getHeight());
        g.setColor(Color.white);
        
        for(int x=20; x< this.getWidth(); x += 40){
        g.drawLine(x, 0, x, this.getHeight());
        }
        for(int y =55; y < this.getHeight(); y += 20){
        g.drawLine(0, y, this.getWidth(), y);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicFoem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicFoem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicFoem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicFoem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicFoem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
